---

mongo:
    extends:
        file: docker-compose-local-db.yml
        service: mongo

redis:
    extends:
        file: docker-compose-local-db.yml
        service: redis

rabbit:
    extends:
        file: docker-compose-local-db.yml
        service: rabbit


nginx:
    extends:
        file: docker-compose-local.yml
        service: nginx

reg:
    extends:
        file: docker-compose-local.yml
        service: reg

mes:
    extends:
        file: docker-compose-local.yml
        service: mes

metrics:
    extends:
        file: docker-compose-local.yml
        service: metrics

admin:
    extends:
        file: docker-compose-local.yml
        service: admin

# uncomment to run the client generation
#gclient:
#    extends:
#        file: docker-compose-local.yml
#        service: gclient
#    volumes:
#        - ./local-dev.conf:/etc/service.conf

spawner:
    extends:
        file: docker-compose-local.yml
        service: spawner

health:
    extends:
        file: docker-compose-local.yml
        service: health