# Test suite for abaco project.
# Image: abaco/testsuite

from abaco/core
ADD tests /tests

RUN chmod +x /tests/entry.sh
entrypoint ["/tests/entry.sh"]
# entrypoint ["py.test", "/tests/test_abaco_core.py"]

