# docker-compose scale spawner=8
version: "3.4"

networks:
    abaco:
        driver: bridge

services:
    # A note on Mongo config. You cannot declare one in this image unless you want to stop using
    # all Docker default config settings. Default script is in /usr/local/bin/docker-entrypoint.sh.
    # This default sets MONGO_INITDB_ROOT_USERNAME/PASS, sets net.bindIp="*", and runs init scripts
    # located inside of /docker-entrypoint-initdb.d. None of this stuff happens if you give your
    # own config (through entrypoint), though, you can provide "command" to give command line arguments.
    # Also, these init scripts and variables are only set on database creation. Restarts will not set
    #them off. Just FYI. This is all stuff the official Mongo image does.
    mongo:
        image: mongo:4.4.7
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
            MONGO_REPLICA_SET_NAME: rs0
        ports:
            - "27017:27017"
        volumes:
            - ./runtime_files/certs:/data/ssl
            - ./runtime_files/certs/mongo-replica-set-keyfile:/keyfiles/metakeyfile
        networks:
            - abaco
        ulimits:
            nproc: 65535
            nofile:
                soft: 65535
                hard: 65535
        # An explanation of this compose file. Mongo backups require replica sets. To do that, you have to
        # create some keys, pass in the keys, ensure key security is 600/700, and then initialize the replica
        # set with `rs.initiate()`. This does all of that, without needing to fork the Mongo image.
        entrypoint:
            - bash
            - -c
            - |
                printf "rs.initiate();\nrs.status()\n" > /docker-entrypoint-initdb.d/mongo-init.js
                cp /keyfiles/metakeyfile /keyfiles/keyfile-to-use
                chmod 400 /keyfiles/keyfile-to-use
                chown 999:999 /keyfiles/keyfile-to-use
                exec docker-entrypoint.sh $$@
        healthcheck:
            test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
            interval: 10s
            start_period: 30s
        command: "mongod --bind_ip_all --replSet $${MONGO_REPLICA_SET_NAME} --keyFile /keyfiles/keyfile-to-use"
        # To enable TLS, uncomment the `command` line below.
        #command: "mongod --bind_ip_all --replSet $${MONGO_REPLICA_SET_NAME} --keyFile /keyfiles/keyfile-to-use --tlsMode requireTLS --tlsCertificateKeyFile "/data/ssl/server.pem" --tlsCAFile "/data/ssl/ca.pem"


    rabbit:
        image: rabbitmq:3.6.12-management
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_NODENAME: abaco-rabbit
            RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "+A 128"
            RABBITMQ_DEFAULT_VHOST: abaco_tacc
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
        ulimits:
            nproc: 65535
            nofile:
                soft: 65535
                hard: 65535
        networks:
            - abaco
        depends_on:
            - mongo

    nginx:
        image: abaco/nginx:$TAG
        volumes:
            - ./config-local.json:/home/tapis/config.json
#            - ./images/nginx/nginx.conf:/etc/nginx/nginx.conf
#            - ./images/nginx/sites-enabled:/etc/nginx/sites-enabled
        ports:
            - "8000:80"
        restart: always
        depends_on:
            - mongo
        networks:
            - abaco

    reg:
        image: abaco/core:$TAG
        ports:
            - "5000:5000"
        volumes:
            - ./config-local.json:/home/tapis/config.json
            - ./abaco.log:/home/tapis/runtime_files/logs/service.log
            - ./runtime_files/certs:/home/tapis/runtime_files/certs
        environment:
            abaco_host_path: ${abaco_path}
            api: reg
            server: gunicorn
            threads: 1
            processes: 1
            timeout: 120
            TAS_ROLE_ACCT:
            TAS_ROLE_PASS:
        depends_on:
            - mongo
        networks:
            - abaco

    mes:
        image: abaco/core:$TAG
        volumes:
            - ./config-local.json:/home/tapis/config.json
            - ./abaco.log:/home/tapis/runtime_files/logs/service.log
            - ./runtime_files/certs:/home/tapis/runtime_files/certs
        ports:
            - "5001:5000"
        environment:
            abaco_host_path: ${abaco_path}
            server: gunicorn
            api: mes
            threads: 3
            processes: 3
            timeout: 120
            TAS_ROLE_ACCT:
            TAS_ROLE_PASS:
        depends_on:
            - mongo
            - reg
        networks:
            - abaco

    admin:
        image: abaco/core:$TAG
        volumes:
            - ./config-local.json:/home/tapis/config.json
            - ./abaco.log:/home/tapis/runtime_files/logs/service.log
            - ./runtime_files/certs:/home/tapis/runtime_files/certs
        ports:
            - "5003:5000"
        environment:
            abaco_host_path: ${abaco_path}
            server: gunicorn
            api: admin
            threads: 1
            processes: 1
            timeout: 120
            TAS_ROLE_ACCT:
            TAS_ROLE_PASS:
        depends_on:
            - mongo
            - reg
        networks:
            - abaco

    spawner:
        image: abaco/core:$TAG
        command: "python3 -u /home/tapis/actors/spawner.py"
        volumes:
            - ./config-local.json:/home/tapis/config.json
            - /var/run/docker.sock:/var/run/docker.sock
            - ./abaco.log:/home/tapis/runtime_files/logs/service.log
            - ./runtime_files/certs:/home/tapis/runtime_files/certs
        environment:
            abaco_host_path: ${abaco_path}
            _abaco_secret: 123
            mongo_password:
            TAS_ROLE_ACCT:
            TAS_ROLE_PASS:
            queue: default
        depends_on:
            - mongo
            - reg
        networks:
            - abaco

    health:
        image: abaco/core:$TAG
        command: /home/tapis/actors/health_check.sh
        volumes:
            - /:/host
            - ./config-local.json:/home/tapis/config.json
            - /var/run/docker.sock:/var/run/docker.sock
            - ./abaco.log:/home/tapis/runtime_files/logs/service.log
            - ./runtime_files/certs:/home/tapis/runtime_files/certs
        environment:
            abaco_host_path: ${abaco_path}
            mongo_password:
            TAS_ROLE_ACCT:
            TAS_ROLE_PASS:
            # add the following pair of credentials for each tenant wanting client generation
            _abaco_DEV-DEVELOP_username: testotheruser
            _abaco_DEV-DEVELOP_password: testotheruser
            _abaco_DEV-STAGING_username: testotheruser
            _abaco_DEV-STAGING_password: testotheruser
        depends_on:
            - mongo
            - reg
        networks:
            - abaco

    events:
        image: abaco/core:$TAG
        command: "python3 -u /home/tapis/actors/events.py"
        volumes:
            - ./config-local.json:/home/tapis/config.json
            - /var/run/docker.sock:/var/run/docker.sock
            - ./abaco.log:/home/tapis/runtime_files/logs/service.log
            - ./runtime_files/certs:/home/tapis/runtime_files/certs
        environment:
            abaco_host_path: ${abaco_path}
            _abaco_secret: 123
            mongo_password:
            TAS_ROLE_ACCT:
            TAS_ROLE_PASS:
            # add the following pair of credentials for each tenant wanting client generation
            _abaco_DEV-DEVELOP_username: testotheruser
            _abaco_DEV-DEVELOP_password: testotheruser
            _abaco_DEV-STAGING_username: testotheruser
            _abaco_DEV-STAGING_password: testotheruser
        depends_on:
            - mongo
            - reg
        networks:
            - abaco

    prometheus:
        # build: ./images/prometheus
        image: abaco/prom:$TAG
        volumes:
            - ./images/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./images/prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
        #   - '-storage.local.path=/prometheus'
        ports:
            - 9090:9090
        networks:
            - abaco
        depends_on:
            - mongo
            - reg

    grafana:
        image: grafana/grafana
        user: "104"
        depends_on:
            - prometheus
            - mongo
            - reg
        ports:
            - 3000:3000
        volumes:
            - grafana_data:/var/lib/grafana
            - ./images/prometheus/grafana/provisioning/:/etc/grafana/provisioning/
        env_file:
            - ./images/prometheus/grafana/config.monitoring
        networks:
            - abaco
        restart: always

    metrics:
        image: abaco/core:$TAG
        networks:
            - abaco
        volumes:
            - ./config-local.json:/home/tapis/config.json
            - ./abaco.log:/home/tapis/runtime_files/logs/service.log
            - ./runtime_files/certs:/home/tapis/runtime_files/certs
        ports:
            - "5004:5000"
        environment:
            abaco_host_path: ${abaco_path}
            server: dev
            api: metrics
            threads: 1
            processes: 1
            timeout: 120
            TAS_ROLE_ACCT:
            TAS_ROLE_PASS:
        depends_on:
            - mongo
            - reg
            - prometheus

volumes:
    grafana_data: {}
