version: "3.3"
services:
    prometheus:
        image: abaco/prom$TAG
#        environment:
#            no_proxy: "reg"
        configs:
          - source: prometheus_config
            target: /etc/prometheus/prometheus.yml
          - source: prometheus_rules
            target: /etc/prometheus/alert.rules.yml
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
        #   - '-storage.local.path=/prometheus'
        ports:
            - 9090:9090
#        networks:
#            - testing
        deploy:
            placement:
                constraints:
                    - 'node.role == manager'
                    - 'node.platform.os == linux'
            resources:
                limits:
                    memory: 500M
                reservations:
                    memory: 200M

#    alertmanager:
#        image: abaco/alert$TAG
##        environment:
##            no_proxy: "gateway"
#        command:
#            - '-config.file=/alertmanager.yml'
#        networks:
#            - testing
#        # Uncomment the following port mapping if you wish to expose the Prometheus
#        # Alertmanager UI.
#        ports:
#             - 9093:9093
#        deploy:
#            resources:
#                limits:
#                    memory: 50M
#                reservations:
#                    memory: 20M
#            placement:
#                constraints:
#                    - 'node.role == manager'
#                    - 'node.platform.os == linux'
#        configs:
#            - source: alertmanager_config
#              target: /alertmanager.yml
#
#
#configs:
#     prometheus_config:
#         file: ./prometheus/prometheus.yml
#     prometheus_rules:
#         file: ./prometheus/alert.rules.yml
#     alertmanager_config:
#         file: ./prometheus/alertmanager.yml
#
#networks:
#    testing:
#        driver: overlay
#        attachable: true
