# Test image for abaco project.
# Image: abaco/test

# Inherit from the abaco image (previously flaskbase):
from abaco/core

USER root


## FILE INITIALIZATION
COPY config-local.json /home/tapis/config-local.json
COPY config-local.json /home/tapis/config.json
COPY tests /home/tapis/tests
RUN chmod +x /home/tapis/tests/entry.sh


## PACKAGE INITIALIZATION
RUN pip3 install pytest ipython #locustio
RUN wget https://raw.githubusercontent.com/rabbitmq/rabbitmq-management/v3.8.9/bin/rabbitmqadmin
RUN chmod +x rabbitmqadmin

# Special flag for tests
ENV _called_from_within_test=True


## PERMISSION INITIALIZATION
USER tapis
ENV PYTHONPATH .:*:actors:actors/*
CMD ["./tests/entry.sh"]
#entrypoint ["/tests/entry.sh"]
