# docker-compose scale spawner=8
version: "3.3"

networks:
    abaco:
        driver: bridge

services:
    # A note on Mongo config. You cannot declare one in this image unless you want to stop using
    # all Docker default config settings. Default script is in /usr/local/bin/docker-entrypoint.sh.
    # This default sets MONGO_INITDB_ROOT_USERNAME/PASS, sets net.bindIp="*", and runs init scripts
    # located inside of /docker-entrypoint-initdb.d. None of this stuff happens if you give your
    # own config (through entrypoint), though, you can provide "command" to give command line arguments.
    # Also, these init scripts and variables are only set on database creation. Restarts will not set them off.
    mongo:
        image: mongo:4.2.6
        #command: --tlsMode requireTLS --tlsCertificateKeyFile "/data/ssl/server.pem" --tlsCAFile "/data/ssl/ca.pem"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
        ports:
            - "27017:27017"
        volumes:
            - /home/trust/abaco/runtime_files/certs:/data/ssl
        networks:
            - abaco
        ulimits:
            nproc: 65535
            nofile:
                soft: 65535
                hard: 65535

    rabbit:
        image: rabbitmq:3.6.12-management
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_NODENAME: abaco-rabbit
            RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "+A 128"
            RABBITMQ_DEFAULT_VHOST: abaco_tacc
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
        ulimits:
            nproc: 65535
            nofile:
                soft: 65535
                hard: 65535
        networks:
            - abaco
        depends_on:
            - mongo

    nginx:
        image: abaco/nginx:$TAG
        volumes:
            - ./config-local.json:/home/tapis/config.json
#            - ./images/nginx/nginx.conf:/etc/nginx/nginx.conf
#            - ./images/nginx/sites-enabled:/etc/nginx/sites-enabled
        ports:
            - "8000:80"
        restart: always
        depends_on:
            - mongo
        networks:
            - abaco

    reg:
        image: abaco/core:$TAG
        ports:
            - "5000:5000"
        volumes:
            - ./config-local.json:/home/tapis/config.json
            - ./abaco.log:/home/tapis/runtime_files/logs/service.log
            - /home/trust/abaco/runtime_files/certs:/home/tapis/runtime_files/certs
        environment:
            abaco_host_path: ${abaco_path}
            api: reg
            server: gunicorn
            threads: 1
            processes: 1
            timeout: 120
            TAS_ROLE_ACCT:
            TAS_ROLE_PASS:
        depends_on:
            - mongo
        networks:
            - abaco

    mes:
        image: abaco/core:$TAG
        volumes:
            - ./config-local.json:/home/tapis/config.json
            - ./abaco.log:/home/tapis/runtime_files/logs/service.log
            - /home/trust/abaco/runtime_files/certs:/home/tapis/runtime_files/certs
        ports:
            - "5001:5000"
        environment:
            abaco_host_path: ${abaco_path}
            server: gunicorn
            api: mes
            threads: 3
            processes: 3
            timeout: 120
            TAS_ROLE_ACCT:
            TAS_ROLE_PASS:
        depends_on:
            - mongo
            - reg
        networks:
            - abaco

    admin:
        image: abaco/core:$TAG
        volumes:
            - ./config-local.json:/home/tapis/config.json
            - ./abaco.log:/home/tapis/runtime_files/logs/service.log
            - /home/trust/abaco/runtime_files/certs:/home/tapis/runtime_files/certs
        ports:
            - "5003:5000"
        environment:
            abaco_host_path: ${abaco_path}
            server: gunicorn
            api: admin
            threads: 1
            processes: 1
            timeout: 120
            TAS_ROLE_ACCT:
            TAS_ROLE_PASS:
        depends_on:
            - mongo
            - reg
        networks:
            - abaco

    spawner:
        image: abaco/core:$TAG
        command: "python3 -u /home/tapis/actors/spawner.py"
        volumes:
            - ./config-local.json:/home/tapis/config.json
            - /var/run/docker.sock:/var/run/docker.sock
            - ./abaco.log:/home/tapis/runtime_files/logs/service.log
            - /home/trust/abaco/runtime_files/certs:/home/tapis/runtime_files/certs
        environment:
            abaco_host_path: ${abaco_path}
            _abaco_secret: 123
            mongo_password:
            TAS_ROLE_ACCT:
            TAS_ROLE_PASS:
            queue: default
        depends_on:
            - mongo
            - reg
        networks:
            - abaco

    health:
        image: abaco/core:$TAG
        command: /home/tapis/actors/health_check.sh
        volumes:
            - /:/host
            - ./config-local.json:/home/tapis/config.json
            - /var/run/docker.sock:/var/run/docker.sock
            - ./abaco.log:/home/tapis/runtime_files/logs/service.log
            - /home/trust/abaco/runtime_files/certs:/home/tapis/runtime_files/certs
        environment:
            abaco_host_path: ${abaco_path}
            mongo_password:
            TAS_ROLE_ACCT:
            TAS_ROLE_PASS:
            # add the following pair of credentials for each tenant wanting client generation
            _abaco_DEV-DEVELOP_username: testotheruser
            _abaco_DEV-DEVELOP_password: testotheruser
            _abaco_DEV-STAGING_username: testotheruser
            _abaco_DEV-STAGING_password: testotheruser
        depends_on:
            - mongo
            - reg
        networks:
            - abaco

    events:
        image: abaco/core:$TAG
        command: "python3 -u /home/tapis/actors/events.py"
        volumes:
            - ./config-local.json:/home/tapis/config.json
            - /var/run/docker.sock:/var/run/docker.sock
            - ./abaco.log:/home/tapis/runtime_files/logs/service.log
            - /home/trust/abaco/runtime_files/certs:/home/tapis/runtime_files/certs
        environment:
            abaco_host_path: ${abaco_path}
            _abaco_secret: 123
            mongo_password:
            TAS_ROLE_ACCT:
            TAS_ROLE_PASS:
            # add the following pair of credentials for each tenant wanting client generation
            _abaco_DEV-DEVELOP_username: testotheruser
            _abaco_DEV-DEVELOP_password: testotheruser
            _abaco_DEV-STAGING_username: testotheruser
            _abaco_DEV-STAGING_password: testotheruser
        depends_on:
            - mongo
            - reg
        networks:
            - abaco

    prometheus:
        # build: ./images/prometheus
        image: abaco/prom:$TAG
        volumes:
            - ./images/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./images/prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
        #   - '-storage.local.path=/prometheus'
        ports:
            - 9090:9090
        networks:
            - abaco
        depends_on:
            - mongo
            - reg

    grafana:
        image: grafana/grafana
        user: "104"
        depends_on:
            - prometheus
            - mongo
            - reg
        ports:
            - 3000:3000
        volumes:
            - grafana_data:/var/lib/grafana
            - ./images/prometheus/grafana/provisioning/:/etc/grafana/provisioning/
        env_file:
            - ./images/prometheus/grafana/config.monitoring
        networks:
            - abaco
        restart: always

    metrics:
        image: abaco/core:$TAG
        networks:
            - abaco
        volumes:
            - ./config-local.json:/home/tapis/config.json
            - ./abaco.log:/home/tapis/runtime_files/logs/service.log
            - /home/trust/abaco/runtime_files/certs:/home/tapis/runtime_files/certs
        ports:
            - "5004:5000"
        environment:
            abaco_host_path: ${abaco_path}
            server: dev
            api: metrics
            threads: 1
            processes: 1
            timeout: 120
            TAS_ROLE_ACCT:
            TAS_ROLE_PASS:
        depends_on:
            - mongo
            - reg
            - prometheus

volumes:
    grafana_data: {}
