---

- include_vars: "{{ abaco_env }}/settings.yml"
- include_vars: "{{ abaco_env }}/passwords.yml"

- name: Compile docker_compose template
  template: src=docker-compose-compute.yml.j2 dest={{ base_dir }}/docker-compose-compute.yml
  sudo: yes
  sudo_user: "{{ linux_user }}"

- name: ensure ipc directories exist
  file: path={{ item }} state=directory
  with_items:
    - '{{ workers_fifo_host_path_dir }}'
    - '{{ workers_socket_host_path_dir }}'
  sudo: yes
  sudo_user: "{{ linux_user }}"

- name: Compile start_spawner.sh template
  template: src=start_spawner.sh.j2 dest={{ base_dir }}/start_spawner.sh
  sudo: yes
  sudo_user: "{{ linux_user }}"

# ignore errors here since this call will fail if there are no containers running
- name: remove existing compute containers
  shell: docker-compose -f  docker-compose-compute.yml down
  sudo: yes
  sudo_user: "{{ linux_user }}"
  ignore_errors: yes

- name: start the containers with docker compose
  shell: docker-compose -f docker-compose-compute.yml up -d & chdir={{ base_dir }}
  sudo: yes
  sudo_user: "{{ linux_user }}"
  environment:
      COMPOSE_HTTP_TIMEOUT: 240
      abaco_path: '{{ base_dir }}'
