# Granting 'actors-serviceaccount' service account the cluster role 'actors-role' which has
# permissions to list/create/get/watch/delete pods and pods/logs.
# Needed for spawner, worker, and health.
# Must create subject for each namespace you want the role to be binded to.

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actors-serviceaccount
    #automountServiceAccountToken: false

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: actors-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services"]
  verbs: ["list", "create", "get", "watch", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: actors-role
subjects:
- kind: ServiceAccount
  name: actors-serviceaccount
  namespace: default
- kind: ServiceAccount
  name: actors-serviceaccount
  namespace: dev
roleRef:
  kind: ClusterRole
  name: actors-role
  apiGroup: rbac.authorization.k8s.io
