
---
apiVersion: v1
kind: Service
metadata:  
  name: actors-nfs
spec:
  selector:    
    app: actors-nfs
  ports:  
  -  port: 2049
     targetPort: 2049

---
apiVersion: v1
kind: Service
metadata:  
  name: actors-nfs-nodeport
spec:
  type: NodePort
  selector:    
    app: actors-nfs
  ports:  
  - port: 2049
    targetPort: 2049

