---

- include_vars: "{{ abaco_env }}/settings.yml"
- include_vars: "{{ abaco_env }}/passwords.yml"

- name: Compile docker_compose template
  template: src=docker-compose-db.yml.j2 dest={{ base_dir }}/docker-compose-db.yml
  sudo: yes
  sudo_user: "{{ linux_user }}"

- name: ensure database containers are running via docker compose
  shell: docker-compose -f docker-compose-db.yml up -d & chdir={{ base_dir }}
  sudo: yes
  sudo_user: "{{ linux_user }}"
